### PR TITLE
Fix the redefinition of ERROR_NEGATIVE_SEEK

### PR DESCRIPTION
**Pull request by gongminmin**
ERROR_NEGATIVE_SEEK is defined twice in MyWindows.h, with different values. Remove the second one to fix the compiling problem on non-Windows platforms.

### CODE REVIEW

**Comment by kornelski** [comment]
Sorry, I don't maintain this code, only copy it from Sourceforge.

You'll have to submit it to: https://sourceforge.net/projects/sevenzip/files/7-Zip/

**Comment by gongminmin** [comment]
But that line of code is introduced in e3dc4878fe2dcd30a8ca53d5d33e55b3f2a9788f, not in sourceforge repository.

**Comment by kornelski** [comment]
Ah, oops.

You can use `original` branch to get exact sourceforge version.
